NTU/urls.py
from django.conf import settings
from django.conf.urls.static import static

from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from news.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("register.urls"), name="reg"),
    path('', include("nav.urls"), name="nav"),
    path('', include("news.urls"), name="new"),
    path('', index, name='index')
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from news import views

app_name = "news"
urlpatterns = [
    path('news/detail/<int:primary_key>/',views.detail,name="detail"),
    path('requests/',views.admin_request_page,name="request"),
    path('requests/detail/article/<int:primary_key>/',views.admin_request_detail_article_page,name="request_detail"),
    path('requests/detail/account/<int:primary_key>/',views.admin_request_detail_account_page,name="request_detail_account"),
    path('articles/list/<int:pk>/',views.articls_page,name="list_articls"),
    path('article/detail/<int:pk>/',views.detail_article_page,name="detail_article"),
    path('article/create/',views.detail_create_article_page,name="create_article"),
    path('article/all/', views.all_article_page,name="all_news"),
    path('article/all/detail/<int:pk>/', views.all_article_detail_page,name="all_detail_news"),
    path('chats/', views.chats, name="chats"),
    path('chat/<str:room_name>/', views.chat, name="chat"),
    path('friends/', views.friends_page,name="friend"),
    path('friend/<str:email>/', views.friend_detail_page,name="friend_detail"),
]

news/models.py
from django.db import models
import datetime
class Tags(models.Model):
    name = models.CharField("Name", max_length=100,default="gello")
    def __str__(self):
        return self.name
class Status(models.Model):
    name = models.CharField("Name", max_length=100,default="Processing")
    def __str__(self):
        return self.name
class StatusMessage(models.Model):
    name = models.CharField("Name", max_length=100, default="Processing")
    def __str__(self):
        return self.name
class StatusChat(models.Model):
    name = models.CharField("Name", max_length=100)
    def __str__(self):
        return self.name
class TypeOfRequest(models.Model):
    name = models.CharField("Name", max_length=100, default="Article")
    def __str__(self):
        return self.name
class TypeOfChat(models.Model):
    name = models.CharField("Name", max_length=100)
    def __str__(self):
        return self.name
class FullStateOfChat(models.Model):
    name = models.CharField("Name", max_length=100)
    def __str__(self):
        return self.name
class PublicationModel(models.Model):
    name = models.CharField("Name", max_length=100)
    title_image = models.ImageField(upload_to='news',default="default.jpg")
    discription = models.TextField("discription")
    author = models.ForeignKey("register.RegistrationModel",on_delete=models.CASCADE,null=True)
    date_of_create = models.DateField(auto_now_add=True,auto_now=False,blank=True)
    time_of_create = models.TimeField(auto_now_add=True,auto_now=False,blank=True)
    date_of_update = models.DateField(auto_now=True,auto_now_add=False,blank=True)
    time_of_update = models.TimeField(auto_now=True,auto_now_add=False,blank=True)
    tags = models.ForeignKey(Tags,on_delete=models.CASCADE,default=0)
    status = models.ForeignKey(Status,on_delete=models.CASCADE,null=True)
    type = models.ForeignKey(TypeOfRequest,on_delete=models.CASCADE,null=True)
    review = models.TextField("Review",blank=True,null=True)
class FriendModel(models.Model):
    surname = models.CharField("Last_Name",max_length=250)
    name = models.CharField("First_Name",max_length=250)
    email = models.EmailField("Email", max_length=100)
    friend = models.ForeignKey("register.RegistrationModel",on_delete=models.CASCADE,null=True)
    owner = models.ForeignKey("register.RegistrationModel",on_delete=models.CASCADE,null=True, related_name="getter")
class MessageModel(models.Model):
    room_name = models.CharField("Room Name",max_length=150)
    message = models.TextField("Message")
    owner = models.ForeignKey("register.RegistrationModel", on_delete=models.CASCADE, null=True, related_name="owner")
    date_of_create = models.DateField(auto_now_add=True,auto_now=False)
    time_of_create = models.TimeField(auto_now_add=True,auto_now=False)
    date_of_update = models.DateField(auto_now=True,auto_now_add=False)
    time_of_update = models.TimeField(auto_now=True,auto_now_add=False)
class ChatModel(models.Model):
    channel_name = models.CharField("Channel Name", max_length=300,null=True)
    room_name = models.CharField("Room Name", max_length=150)
    name = models.CharField("First Name", max_length=250,null=True)
    surname = models.CharField("Last Name", max_length=250,null=True)
    participant = models.ForeignKey("register.RegistrationModel", on_delete=models.CASCADE,null=True,related_name="participant")
    active = models.BooleanField("Active Chat",default=False)
    status = models.ForeignKey(StatusChat,on_delete=models.CASCADE,null=True)
    type_chat = models.ForeignKey(TypeOfChat,on_delete=models.CASCADE,null=True)
    full_state = models.ForeignKey(FullStateOfChat,on_delete=models.CASCADE,null=True)

news/forms.py
from news.models import PublicationModel,Tags,Status
from django.forms import ModelForm, TextInput, PasswordInput, CheckboxInput, Textarea, FileInput, NumberInput,BaseForm,Form
from django import forms
class PublicationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(PublicationForm, self).__init__(*args, **kwargs)
        self.fields["review"].required = True
    class Meta:
        model = PublicationModel
        exclude = ('name', 'discription','title_image', 'author', 'date_of_create','time_of_create','date_of_update','time_of_update','tags','status','type')
        fields = ['review']
        widgets = {
            "review": Textarea(attrs={
                "class": "form-control",
                "type": "text",
                "id": "Review",
                "name": "Review"
            }),
        }
class ArticleForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.fields["tags"] = forms.ModelChoiceField(queryset=Tags.objects.all())
        self.fields["name"] = forms.CharField(label="Title",widget=TextInput(attrs={
                "class": "form-control",
                "type": "text",
                "id": "discription",
                "name": "discription"
            }),)
    class Meta:
        model = PublicationModel
        fields = ['name','discription','tags','title_image']
        widgets = {
            "discription": Textarea(attrs={
                "class": "form-control",
                "type": "text",
                "id": "discription",
                "name": "discription"
            }),
        }
class NewsForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(NewsForm, self).__init__(*args, **kwargs)
        self.fields['status'] = forms.ModelChoiceField(queryset=Status.objects.all())
        self.fields["review"].required = True
    class Meta:
        model = PublicationModel
        exclude = ('name', 'discription', 'title_image', 'author', 'date_of_create', 'time_of_create', 'date_of_update','time_of_update', 'tags','type')
        fields = ['status','review']
        widgets = {
            'review': Textarea(attrs={
                "class": "form-control",
                "type": "text",
                "id": 'review',
                "name": 'review'
            }),
        }
class AccountForm(Form):
    reason = forms.CharField(widget=forms.Textarea(attrs={
        "class": "form-control",
        "type": "text",
        "id": "Reason",
        "name": "Reason"
    }))

news/views.py
import string
import random
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.shortcuts import render,redirect
from django.urls import reverse
from news.models import PublicationModel,Status,TypeOfRequest,FriendModel,MessageModel,ChatModel,StatusChat,FullStateOfChat
from register.models import RegistrationModel,Role
from django.contrib.postgres.search import SearchVector,SearchQuery,TrigramSimilarity
from news.forms import PublicationForm, AccountForm,ArticleForm,NewsForm
from django.db.models import Q
def get_last_room_name(request):
    chat = MessageModel.objects.filter(sender__email=request.session["Email"]).order_by("-date_of_update","-time_of_update")[0]
    return str(chat.room_name)
def index(request):
    if request.method == "POST":
        if request.POST.get("search"):
            query = SearchQuery(request.POST.get("search"),config='Russian',search_type='websearch')
            search_news = PublicationModel.objects.annotate(search=SearchVector("author","name","discription",config='Russian')).filter(search=query)
            search_similarity_name_news = PublicationModel.objects.annotate(similarity=TrigramSimilarity("name",request.POST.get("search"))).filter(similarity__gt=0.03).order_by('-similarity')
            search_similarity_discription_news = PublicationModel.objects.annotate(similarity=TrigramSimilarity("discription", request.POST.get("search"))).filter(similarity__gt=0.03).order_by('-similarity')
            search_similarity_author_news = PublicationModel.objects.annotate(similarity=TrigramSimilarity("author", request.POST.get("search"))).filter(similarity__gt=0.03).order_by('-similarity')
            return render(request, 'news/news.html', locals())
        if request.POST.get("filter"):
            filter = request.POST.getlist("filter")
            filters = PublicationModel.objects.filter(tags__name__in=filter)
            return render(request, 'news/news.html', locals())
    try:
        if request.session["Auth"]:
            news = PublicationModel.objects.filter(status__name="Accept").order_by("-date_of_update", "-time_of_update")
            response = render(request, 'news/news.html', locals())
            response.set_cookie("Email",request.session["Email"])
            return response
        else:
            news = PublicationModel.objects.filter(status__name="Accept").order_by("-date_of_update", "-time_of_update")
            return render(request, 'news/news.html', locals())
    except KeyError:
        news = PublicationModel.objects.filter(status__name="Accept").order_by("-date_of_update", "-time_of_update")
        return render(request, 'news/news.html', locals())
def detail(request,primary_key):
    if request.method == "POST":
        if request.POST.get("email"):
            number = ''.join(random.choices(string.ascii_lowercase + string.digits, k=9))
            exist = ChatModel.objects.filter(room_name=number,participant__email=request.session["Email"]).exists()
            if exist:
                return redirect(reverse("news:chat"))
            else:
                if request.session["Email"] == request.POST.get("email"):
                    return redirect("/")
                else:
                    owner = RegistrationModel.objects.get(email=request.session["Email"])
                    guest = RegistrationModel.objects.get(email=request.POST.get("email"))
                    full =  FullStateOfChat.objects.get("Full")
                    empty = FullStateOfChat.objects.get("Clean")
                    disable = StatusChat.objects.get(name="Disable")
                    wait = StatusChat.objects.get(name="Wait")
                    chat1 = ChatModel(room_name=number, name=owner.first_name, surname=owner.last_name,participant=owner, active=True, status=wait, full_state=empty)
                    chat2 = ChatModel(room_name=number, name=guest.first_name, surname=guest.last_name,participant=guest, active=False, status=disable, full_state=empty)
                    chat1.save()
                    chat2.save()
                    return redirect(reverse("news:chats"))
    news = PublicationModel.objects.get(pk=primary_key)
    return render(request, 'news/detail_news.html', locals())
def admin_request_page(request):
    if request.session["Role"] != "Admin":
        return redirect("/")
    else:
        news = PublicationModel.objects.filter(status__name="Processing")
        accounts = RegistrationModel.objects.filter(status__name="Processing")
        return render(request, 'news/request.html', locals())
def admin_request_detail_article_page(request,primary_key):
    if request.session["Role"] != "Admin":
        return redirect("/")
    else:
        news = PublicationModel.objects.get(pk=primary_key)
        if request.method == "POST":
            if request.POST.get('Accept'):
                 b = Status.objects.get(name="Accept")
                 PublicationModel.objects.filter(id=primary_key).update(status=b.id)
                 return redirect(reverse("news:request"))
            else:
                forms = PublicationForm(request.POST,instance=news)
                if forms.is_valid():
                    form = forms.save(commit=False)
                    b = Status.objects.get(name="Refuse")
                    form.status_id = b.id
                    form.save()
                    return redirect(reverse("news:request"))
        forms = PublicationForm(instance=news)
        return render(request, 'news/datail_article_request.html', locals())
def admin_request_detail_account_page(request,primary_key):
    if request.session["Role"] != "Admin":
        return redirect("/")
    else:
        accounts = RegistrationModel.objects.get(pk=primary_key)
        if request.method == "POST":
            data = RegistrationModel.objects.filter(id=primary_key)[0]
            if request.POST.get('Accept'):
                 status = Status.objects.get(name="Accept")
                 role = Role.objects.get(name="Moderator")
                 RegistrationModel.objects.filter(id=primary_key).update(status=status.id,role=role.id)
                 send_raise_level_account_email(data.email)
                 return redirect(reverse("news:request"))
            else:
                forms = AccountForm(request.POST)
                if forms.is_valid():
                    letter = forms.cleaned_data["reason"]
                    send_recomandation_email(data.email,letter)
                    return redirect(reverse("news:request"))
        form = AccountForm()
        return render(request, 'news/detail_account_request.html', locals())
def articls_page(request,pk):
    if request.session["Role"] != "Moderator" and request.session["Role"] != "Admin":
        return redirect("/")
    else:
        articles = PublicationModel.objects.filter(author=pk)
        return render(request, 'news/articls.html', locals())
def detail_article_page(request,pk):
    if request.session["Role"] != "Moderator" and request.session["Role"] != "Admin":
        return redirect("/")
    else:
        article = PublicationModel.objects.get(id=pk)
        if request.method == "POST":
            if request.POST.get("delete"):
                article.delete()
                return redirect(reverse("news:list_articls", args=(request.session.get("id"),)))
            else:
                forms = ArticleForm(request.POST,request.FILES,instance=article)
                if forms.is_valid():
                    form = forms.save(commit=False)
                    status = Status.objects.get(name="Processing")
                    form.status_id = status.id
                    form.save()
                    return redirect(reverse("news:list_articls",args=(request.session.get("id"),)))
        try:
            len_review = len(article.review)
        except TypeError:
            len_review = 0
        forms = ArticleForm(instance=article)
        return render(request, 'news/detail_article_moderator.html', locals())
def detail_create_article_page(request):
    if request.session["Role"] != "Moderator" and request.session["Role"] != "Admin":
        return redirect("/")
    else:
        if request.method == "POST":
            forms = ArticleForm(request.POST,request.FILES)
            if forms.is_valid():
                form = forms.save(commit=False)
                status = Status.objects.get(name="Processing")
                status2 = Status.objects.get(name="Accept")
                author = RegistrationModel.objects.get(id=int(request.session.get("id")))
                type = TypeOfRequest.objects.get(name="Article")
                if request.session["Role"] == "Admin":
                    form.status_id = status2.id
                else:
                    form.status_id = status.id
                form.author_id = author.id
                form.type_id = type.id
                form.save()
                return redirect(reverse("news:list_articls", args=(request.session.get("id"),)))
        forms = ArticleForm()
        return render(request, 'news/detail_create_article_moderator.html', locals())
def all_article_page(request):
    if request.session["Role"] != "Admin":
        return redirect("/")
    else:
        if request.method == "POST":
            if request.POST.get("filter"):
                filters = PublicationModel.objects.filter(status__name__in=request.POST.getlist("filter"))
                return render(request, 'news/all_article.html', locals())
        news = PublicationModel.objects.all()
        return render(request,'news/all_article.html',locals())
def all_article_detail_page(request,pk):
    if request.session["Role"] != "Admin":
        return redirect("/")
    else:
        new = PublicationModel.objects.get(id=pk)
        if request.method == "POST":
            forms = NewsForm(request.POST,instance=new)
            if forms.is_valid():
                forms.save()

templates/news/all_article.html
{% extends 'base.html' %}
{% block filter %}
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Filters</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Filters:</h6>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="filter" value="Accept" id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">
                        Accept
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="filter" value="Proccesing" id="flexCheckChecked">
                        <label class="form-check-label" for="flexCheckChecked">
                        Proccesing
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="filter" value="Refuse" id="flexCheckChecked">
                        <label class="form-check-label" for="flexCheckChecked">
                        Refuse
                        </label>
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm">Find</button>
                </form>
            </div>
        </div>
    </li>
{% endblock %}
{% block content %}
<div class="row">
{% if news %}
    {% for new in news %}
        <div class="col-lg-12">
            <div class="card mb-3" style="width: 900px; height: 300px;">
                <div class="row g-0">
                    <div class="col-md-5">
                        {% if new.title_image.name == "default.jpg" %}
                            <img src="/media/news/{{new.title_image.name}}" class="img-fluid" alt="..." style="height: 300px;">
                        {% else %}
                            <img src="/media/{{new.title_image.name}}" class="img-fluid" alt="..." style="height: 300px;">
                        {% endif %}
                    </div>
                    <div class="col-md-7">
                        <div class="card-body">
                            <a href="{% url "news:all_detail_news" new.id %}"><h5 class="card-title">{{new.name}}</h5></a>
                            <p class="card-text">{{new.discription|truncatewords:20}}</p>
                            <p class="card-text"><small class="text-muted">Status: {{new.status.name}}</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% elif filters %}
    {% for filter in filters %}
        <div class="col-lg-12">
            <div class="card mb-3" style="width: 900px; height: 300px;">
                <div class="row g-0">
                    <div class="col-md-5">
                        {% if filter.title_image.name == "default.jpg" %}
                            <img src="/media/news/{{filter.title_image.name}}" class="img-fluid" alt="..." style="height: 300px;">
                        {% else %}
                            <img src="/media/{{filter.title_image.name}}" class="img-fluid" alt="..." style="height: 300px;">
                        {% endif %}
                    </div>
                    <div class="col-md-7">
                        <div class="card-body">
                            <a href="{% url "news:all_detail_news" filter.id %}"><h5 class="card-title">{{filter.name}}</h5></a>
                            <p class="card-text">{{filter.discription|truncatewords:20}}</p>
                            <p class="card-text"><small class="text-muted">Status: {{filter.status.name}}</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}
</div>
{% endblock %}

templates/news/articls.html
{% extends "base.html"%}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-primary" href="{% url "news:create_article" %}" role="button">+</a>
    </div>
    {% for article in articles %}
        <div class="col-lg-12">
            <div class="card mb-3" style="width: 787px; height: 248px;">
                <div class="row g-0">
                    <div class="col-md-5">
                        {% if article.title_image.name == "default.jpg" %}
                            <img src="/media/news/{{article.title_image.name}}" class="img-fluid rounded-start" alt="..." style="height: 248px;">
                        {% else %}
                            <img src="/media/{{article.title_image.name}}" class="img-fluid rounded-start" alt="..." style="height: 248px;">
                        {% endif %}
                    </div>
                    <div class="col-md-7">
                        <div class="card-body">
                            <a href="{% url "news:detail_article" article.id %}"><h5 class="card-title">{{article.name}}</h5></a>
                            <p class="card-text">{{article.discription|truncatewords:20}}</p>
                            <p class="card-text"><small class="text-muted">Status: {{article.status.name}}</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/news/datail_article_request.html
{% extends "base.html" %}
{% block content %}
<h3>Title:</h3>
<p>{{ news.name }}</p>
<h3>Image:</h3>
{% if news.title_image.name == "default.jpg" %}
    <img src="/media/news/{{news.title_image.name}}" class="img-fluid py-3" alt="...">
{% else %}
    <img src="/media/{{news.title_image.name}}" class="img-fluid py-3" alt="...">
{% endif %}
<h3>Description:</h3>
<p>{{ news.discription }}</p>
<form method="post" class="my-3" id="form">
    {% csrf_token %}
    {% for form in forms %}
        {% if form.errors %}
            {% for error in form.errors%}
                    <div class="mb-3 w-25">
                            <label class="form-label">{{form.label}}</label>
                            {{ form }}
                            <p style="margin-top:10px; color:red;">{{ error }}</p>
                    </div>
            {% endfor %}
        {% else %}
                <div class="mb-3 w-25">
                    <label class="form-label">{{form.label}}</label>
                    {{ form }}
                </div>
        {% endif %}
    {% endfor %}
</form>
<form method="post" id="form2">
    {% csrf_token %}
    <input type="hidden" name="Accept" value="true"></input>
</form>
<p class="text"><small class="text-muted">Status: {{news.status.name}}</small></p>
<p class="text"><small class="text-muted">Type: {{news.type.name}}</small></p>
<button type="submit" form="form2" class="btn btn-success mx-3" id="accept">Accept article</button>
<button type="submit" form="form" class="btn btn-danger mx-4" id="decline">Decline article</button>
{% endblock %}

templates/news/detail_account_request.html
{% extends "base.html" %}
{% block content %}
<h4>First name: {{ accounts.first_name }}</h4>
<h4>Surname: {{ accounts.last_name }}</h4>
<h4>Email: {{ accounts.email }}</h4>
<form method="post" class="my-3" id="form">
    {% csrf_token %}
    <div class="mb-3 w-25">
        <label class="form-label">{{form.label}}</label>
        {{ form }}
    </div>
</form>
<form method="post" id="form2">
    {% csrf_token %}
    <input type="hidden" name="Accept" value="true"></input>
</form>
<p class="text"><small class="text-muted">Status: {{accounts.status.name}}</small></p>
<p class="text"><small class="text-muted">Type: {{accounts.type.name}}</small></p>
<button type="submit" form="form2" class="btn btn-success mx-3" id="accept">Raise level account</button>
<button type="submit" form="form" class="btn btn-danger mx-4" id="decline">Don't change level account</button>
{% endblock %}

templates/news/detail_article.html
{% extends "base.html" %}
{% block content %}
<h3>Title:</h3>
<p>{{ new.name }}</p>
<h3>Image:</h3>
{% if new.title_image.name == "default.jpg" %}
    <img src="/media/news/{{new.title_image.name}}" class="img-fluid py-3" alt="...">
{% else %}
    <img src="/media/{{new.title_image.name}}" class="img-fluid py-3" alt="...">
{% endif %}
<h3>Description:</h3>
<p>{{ new.discription }}</p>
<form method="post" class="my-3" id="form">
    {% csrf_token %}
    {% for form in forms %}
        {% if form.errors %}
            {% for error in form.errors%}
                    <div class="mb-3 w-25">
                            <label class="form-label">{{form.label}}</label>
                            {{ form }}
                            <p style="margin-top:10px; color:red;">{{ error }}</p>
                    </div>
            {% endfor %}
        {% else %}
                <div class="mb-3 w-25">
                    <label class="form-label">{{form.label}}</label>
                    {{ form }}
                </div>
        {% endif %}
    {% endfor %}
</form>
<button type="submit" form="form" class="btn btn-success">Update</button>
{% endblock %}

templates/news/detail_article_moderator.html
{% extends "base.html"%}
{% block content %}
<form method="post" enctype="multipart/form-data" id="form">
    {% csrf_token %}
    {% for form in forms %}
        <div class="mb-3 w-25">
            <label class="form-label">{{form.label}}:</label>
            {{ form }}
        </div>
    {% endfor %}
</form>
<form method="post" id="form2">
    {% csrf_token %}
    <input type="hidden" name="delete" value="true">
</form>
<h3>Image:</h3>
{% if article.title_image.name == "default.jpg" %}
    <img src="/media/news/{{article.title_image.name}}" class="img-fluid py-3" alt="...">
{% else %}
    <img src="/media/{{article.title_image.name}}" class="img-fluid py-3" alt="...">
{% endif %}
{% if len_review.len_review != 0 %}
    <h3>Re:</h3>
    <p class="text mx-3">{{article.review}}</p>
{% endif %}
<p class="text"><small class="text">Status: {{article.status.name}}</small></p>
<button type="submit" class="btn btn-success" form="form">Update</button>
<button type="submit" class="btn btn-danger mx-5" form="form2">Delete</button>
{% endblock %}

templates/news/friends.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class='col-lg-12'>
        <ul class="list-unstyled mb-0" style="max-height: 800px; overflow-y:scroll;overflow-x:hidden; height: 680px;">
            <div class="input-group rounded mb-3">
                <form id="form" method="post">
                    {% csrf_token %}
                    <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" name="Find"/>
                </form>
                <button type="submit" form="form" class="btn btn-primary"><i class="fas fa-search"></i></button>
            </div>
            {% if friends %}
                {% for friend in friends %}
                    <li class="p-2 border-bottom" style="background-color: #eee;">
                        <a href="#!" class="d-flex justify-content-between">
                        <div class="d-flex flex-row">
                            {% if friend.friend.photo.name == "depositphotos_199564354-stock-illustration-creative-vector-illustration-of-default.jpg" %}
                                <img src="/media/profile/{{friend.friend.photo.name}}" alt="avatar" class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                            {% else %}
                                <img src="/media/{{friend.friend.photo.name}}" alt="avatar" class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                            {% endif %}
                            <div class="pt-1">
                            <a href="{% url "news:friend_detail" friend.email %}"><p class="fw-bold mb-0">{{friend.friend.last_name}} {{friend.friend.first_name}}</p></a>
                            </div>
                        </div>
                        </a>
                    </li>
                {% endfor %}
            {% elif friend %}
                <li class="p-2 border-bottom" style="background-color: #eee;">
                    <a href="#!" class="d-flex justify-content-between">
                    <div class="d-flex flex-row">
                        {% if friend.photo.name == "depositphotos_199564354-stock-illustration-creative-vector-illustration-of-default.jpg" %}
                            <img src="/media/profile/{{friend.photo.name}}" alt="avatar" class="rounded-circle " width="60">
                        {% else %}
                            <img src="/media/{{friend.photo.name}}" alt="avatar" class="rounded-circle" width="60">
                        {% endif %}
                        <div class="pt-1">
                            <a href="{% url 'news:friend_detail' friend.email %}"><p class="fw-bold mb-0">{{friend.last_name}} {{friend.first_name}}</p></a>
                        </div>
                    </div>
                    </a>
                </li>
            {% else %}
                <div class="d-flex justify-content-center my-5">
                    <h2>No any friends</h2>
                </div>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}